name: DeepSource Test Coverage

on:
  push:
    branches:
      - main

jobs:
  deepsource:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Upload coverage report to DeepSource
        uses: deepsourcelabs/test-coverage-action@v1
        with:
          api-key: ${{ secrets.DS_API_KEY }}
