name: Code Coverage with DeepSource

on:
  push:
    branches:
      - main  # Adjust this to your default branch

jobs:
  deepsource:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Install any dependencies your project needs
          # For example, pip install -r requirements.txt

      - name: Run tests
        run: |
          # Run your tests and generate the coverage report
          # For example, pytest --cov=my_module tests/

      - name: Report test coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: python  # Replace with your programming language (e.g., go, javascript)
          coverage-file: coverage.xml  # Path to your coverage data file
          dsn: ${{ secrets.DEEPSOURCE_DSN }}  # Add your DeepSource DSN secret

          # Optional: Set to true if you want the CI build to fail on error
          fail-ci-on-error: false
